# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# default_platform(:ios)

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

desc 'UpdatePod 航道用来自动化升级维护私有库'
lane :UpdatePod do |options|

tagNum = options[:tag]
podspecName = options[:specName]

# 航道上需要执行的操作
# 具体action到 https://docs.fastlane.tools/actions 上面查找
# 这里的路径以仓库根目录为准

# 1、修改spec文件（修改s.version，s.description等）
# 2、pod install （使Example与pod下来的库产生关联）
cocoapods(
  clean: true,
  podfile: "./Example/Podfile",
  use_bundle_exec: false
)


# 3、提交本地仓库代码至远程仓库
git_add(path: ".")
git_commit(path: ".", message: "upgrade repo")
push_to_git_remote


# 4、打标签，并提交至远程
# 先验证tag是否存在，如果存在则删除本地标签和远程标签
if git_tag_exists(tag: tagNum)
  UI.message("您输入的tag:#{tagNum}已存在，即将自动清除") 
  remove_git_tag(tagNum: tagNum)
end
add_git_tag(
  tag: tagNum
)
push_git_tags


# 5、验证spec，并提至私有索引库
pod_lib_lint(allow_warnings:true,skip_import_validation:true)
# podspec的名字需要由外界传入
# pod_push(path: "#{podspecName}.podspec", repo: "iosSpec")
command_action(cmd:"pod trunk push #{podspecName}.podspec --allow-warnings --skip-import-validation'")


end
